[project]
name = "agenticai-billing-kb-main"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GiselaInge", email = "118785545+kugguk2022@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
agenticai-billing-kb-main = "agenticai_billing_kb_main:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
